name: Ilk MLOps Avtomatlasdirilmasi

on:
  push:
    branches:
      - main

jobs:
  modeli-yoxla-ve-qur:
    runs-on: ubuntu-latest

    steps:
    - name: Kodlari bura kocur
      uses: actions/checkout@v4  # v3-ü v4 etdik

    - name: Python-u qurasdir
      uses: actions/setup-python@v5  # v4-ü v5 etdik
      with:
        python-version: '3.11'

    - name: Kitabxanalar yukle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Modeli avtomatik oyret (Train)
      run: |
        python train.py